<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "glshop"
 *
 * Auto generated by Extension Builder 2019-03-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Glacryl Shop System',
    'description' => 'Dies ist ein Shopsystem für Glacryl Hedel GmbH basierend auf TYPO3 9.5',
    'category' => 'plugin',
    'author' => 'Petro Dikij',
    'author_email' => 'petro.dikij@glacryl.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'extbase' => '9.5',
            'fluid' => '9.5',
            'typo3' => '9.5',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
