<?php

function getAB() {
    $html = '<!DOCTYPE html>';
    $html .= '<html>';
    $html .= '<head>';
    $html .= '<title></title>';
    $html .= '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
    $html .= '<link rel="stylesheet" type="text/css" href="style.css" media="all">';
    $html .= '</head>';
    $html .= '<body>';

    $html .= '<!--mpdf';
    $html .= '<htmlpageheader name="myheader">';
    $html .= '<div class="logo">';
    $html .= '<img src="imgs/logo.jpg" />';
    $html .= '</div>';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="header">';
    $html .= '<div class="adresse">';
    $html .= '<p>Herrn</p>';
    $html .= '<p>Max Mustermann</p>';
    $html .= '<p>Muster Str. 5</p>';
    $html .= '<p></p>';
    $html .= '<p>91522 Ansbach</p>';
    $html .= '</div>';
    $html .= '<div class="infoDaten">';
    $html .= '<p>AUFTRAGSBEST&Auml;TIGUNG</p>';
    $html .= '<table>';
    $html .= '<tr>';
    $html .= '<td>Auftrag Nummer</td>';
    $html .= '<td>A1</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>Kunden-Nummer</td>';
    $html .= '<td>7</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>Datum</td>';
    $html .= '<td>21.12.2011</td>';
    $html .= '</tr>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</htmlpageheader> ';

    $html .= '<htmlpagefooter name="myfooter">';
    $html .= '<div class="footer">';
    $html .= '<div class="footerText">';
    $html .= '<p>';
    $html .= 'Die Ware bleibt bis zur vollständigen Bezahlung unser Eigentum. Ferner gilt der erweiterte Eigentumsvorbehalt, sowie ein Be- und Verarbeitungsvorbehalt als vereinbart. Gerichtsstand ist Ansbach.';
    $html .= '</p>';
    $html .= '</div>';
    $html .= '<div class="footerInfo">';
    $html .= '<div class="fTelefon">';
    $html .= '<p>Telefon (0981) 23 38</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '<p>Telefax (0981) 1 79 51</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '</div>';
    $html .= '<div class="fAnschrift">';
    $html .= '<p><b>Hausanschrift</b></p>';
    $html .= '<p>Glacryl Hedel GmbH</p>';
    $html .= '<p>Naumannstr. 13</p>';
    $html .= '<p>91522 Ansbach</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '</div>';
    $html .= '<div class="fGericht">';
    $html .= '<p><b>Reg.-Gericht Ansbach</b></p>';
    $html .= '<p>HRB 1495</p>';
    $html .= '<p>Wolfgang Hedel</p>';
    $html .= '<p>Gesch&auml;ftsf&uuml;hrer</p>';
    $html .= '<p>Ust-IdNr. DE131938998</p>';
    $html .= '<p>St-Nr. 203/127/50059</p>';
    $html .= '</div>';
    $html .= '<div class="fBankd">';
    $html .= '<p>Postbank Nürnberg</p>';
    $html .= '<p>Sparkasse Ansbach</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '</div>';
    $html .= '<div class="fKonto">';
    $html .= '<p>(BLZ 760 100 85) Kto. 125 65-854</p>';
    $html .= '<p>(BLZ 765 500 00) Kto. 291 807</p>';
    $html .= '<p>IBAN: DE74 7655 0000 0000 2918 07</p>';
    $html .= '<p>BIC: BYLADEM1ANS</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '<p>&nbsp;</p>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</htmlpagefooter>';

    $html .= '<sethtmlpageheader name="myheader" value="on" show-this-page="1" />';
    $html .= '<sethtmlpagefooter name="myfooter" value="on" />';
    $html .= 'mpdf-->';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="content">';
    $html .= '<div>';
    $html .= '<p style="font-weight: bold; margin-bottom: 10px;">Sehr geehrte Damen und Herren,</p>';
    $html .= '<p>Wir danken für Ihren Auftrag und fertigen bzw. liefern nach unseren Allgemeinen Geschäftsbedingungen folgende Positionen:</p>';
    $html .= '</div>';
    $html .= '<div class="positionenTabelle">';
    $html .= '<table>';
    $html .= '<thead>';
    $html .= '<tr valign="bottom">';
    $html .= '<th width="50px" valign="bottom">Position</th>';
    $html .= '<th width="280px" valign="bottom" style="text-align: left;">Bezeichnung</th>';
    $html .= '<th width="100px" valign="bottom">Breite x H&ouml;he (mm)</th>';
    $html .= '<th width="50px" valign="bottom">Anzahl</th>';
    $html .= '<th width="80px" valign="bottom">Einzelpreis inkl. Bearbeitung</th>';
    $html .= '<th width="90px" valign="bottom" style="text-align: right;">Gesamtpreis (netto)</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td style="text-align: center;" valign="top">1</td>';
    $html .= '<td style="text-align: left;">';
    $html .= '<span class="position">Acrylglas XT 5mm</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x facettierte & polierte Kante:</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">je 2mm 45&deg;</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x Rundecke</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x Wandabstandshalter:</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">Messing, poliert</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">Art. GL.000.000.001</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">2 x Bohrung</span>';
    $html .= '</td>';
    $html .= '<td style="text-align: center;">1000x1000</td>';
    $html .= '<td style="text-align: center;">2</td>';
    $html .= '<td style="text-align: center;">10,50 &euro;</td>';
    $html .= '<td style="text-align: right;">23,00 &euro;</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="last" style="text-align: center;" valign="top">2</td>';
    $html .= '<td class="last" style="text-align: left;">';
    $html .= '<span class="position">Klemmschildhalter ohne Platenbohrung</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">Messing, poliert, verchormt</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">Art. GL.3213.5454.3215</span>';
    $html .= '</td>';
    $html .= '<td class="last" style="text-align: center;"></td>';
    $html .= '<td class="last" style="text-align: center;">20</td>';
    $html .= '<td class="last" style="text-align: center;">2,00 &euro;</td>';
    $html .= '<td class="last" style="text-align: right;">40,00 &euro;</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '<div class="zusammenFassungPreise">';
    $html .= '<table>';
    $html .= '<tr>';
    $html .= '<td class="beschriftung">Zwischensumme</td>';
    $html .= '<td class="wert">63,00 &euro;</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="beschriftung">Mengenrabatt (3%)</td>';
    $html .= '<td class="wert">1,89 &euro;</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="beschriftung">MwSt (19%)</td>';
    $html .= '<td class="wert">11,61 &euro;</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="beschriftung">Verpackung & Versand</td>';
    $html .= '<td class="wert">6,90 &euro;</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="beschriftung">Gesamt</td>';
    $html .= '<td class="wert">79,62 &euro;</td>';
    $html .= '</tr>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '<div>';
    $html .= '<table border="0" style="border-collapse: collapse;margin-left: -1px;">';
    $html .= '<tr style="height: 45px">';
    $html .= '<td valign="top">Zahlungsbed.:</td>';
    $html .= '<td valign="top">Bei Zahlung innerhalb von 14 Tagen 3% Skonto<br/>ansonsten innerhalb von 30 Tagen netto.</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>Lieferadresse:</td>';
    $html .= '<td>wie oben bzw. abweichende Lieferanschrift</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td colspan="2">Bitte überprüfen Sie oben stehende Maß- und Mengenangaben.</td>';
    $html .= '</tr>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '<div style="margin-top: 10px;">';
    $html .= '<p>Um eine fach- und termingerechte Ausführung bemüht zeichnen wir <br />mit freundlichen Grüßen</p>';
    $html .= '<p style="margin-top: 30px;">GLACRYL Hedel GmbH</p>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</body>';
    $html .= '</html>';
    return $html;
}
?>