<?php

function getFe() {
    $html = '<!DOCTYPE html>';
    $html .= '<html>';
    $html .= '<head>';
    $html .= '<title></title>';
    $html .= '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
    $html .= '<link rel="stylesheet" type="text/css" href="styleFe.css" media="all">';
    $html .= '</head>';
    $html .= '<body>';

    $html .= '<!--mpdf';
    $html .= '<htmlpageheader name="myheader">';
    $html .= '<div class="header">';
    $html .= '<div class="adresse">';
    $html .= '<p>Herrn</p>';
    $html .= '<p>Max Mustermann</p>';
    $html .= '<p>Muster Str. 5</p>';
    $html .= '<p></p>';
    $html .= '<p>91522 Ansbach</p>';
    $html .= '</div>';
    $html .= '<div class="logo">';
    $html .= '<img src="imgs/logo.jpg" />';
    $html .= '</div>';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="barcode">';
    $html .= '<span>2</span>';
    $html .= '<barcode code="P.3.1" type="C39" class="barcode" />';
    $html .= '</div>';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="infoDaten">';
    $html .= '<table>';
    $html .= '<thead>';
    $html .= '<tr>';
    $html .= '<th style="font-size: 1.3em;">Fertigungsschein-Nr.</th>';
    $html .= '<th style="font-size: 1.3em;">2</th>';
    $html .= '<td class="tRight" style="text-align: right;">Datum:</td>';
    $html .= '<td>14.04.2013</td>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td>zu Auftrag</td>';
    $html .= '<td>I2</td>';
    $html .= '<td class="tRight">Termin:</td>';
    $html .= '<td>KW18</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>Kunden-Nummer</td>';
    $html .= '<td>2</td>';
    $html .= '<td class="tRight">Bearbeiter:</td>';
    $html .= '<td>Herr Dikij</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</htmlpageheader> ';

    $html .= '<sethtmlpageheader name="myheader" value="on" show-this-page="1" />';
    $html .= '<sethtmlpagefooter name="myfooter" value="on" />';
    $html .= 'mpdf-->';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="content">';
    $html .= '<div>';
    $html .= '<div style="width: 470px; float:left;">';
    $html .= '<table style="width: 100%; border-collapse: collapse;">';
    $html .= '<tr>';
    $html .= '<td>Ansprechpartner:</td>';
    $html .= '<td>Hr. Mustermann +49/ 981 95 25 162</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>zuges. Liefertermin:</td>';
    $html .= '<td>KW 18</td>';
    $html .= '</tr>';
    $html .= '<tr>         ';
    $html .= '<td>Lieferbedingung:</td>';
    $html .= '<td>Selbstabholer</td>';
    $html .= '</tr>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '<div style="width: 185px; float:right;">';
    $html .= '<table style="border-collapse: collapse; width: 100%;" border="1">';
    $html .= '<tr>';
    $html .= '<td colspan="3" style="text-align: center;">Glas befindet sich in</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td style="text-align: center;">Schieber Nr.:</td>';
    $html .= '<td style="text-align: center;">oben</td>';
    $html .= '<td style="text-align: center;">unten</td>';
    $html .= '</tr>';
    $html .= '<tr>         ';
    $html .= '<td style="font-size: 1.2em;">&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '</tr>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '<div class="positionenTabelle">';
    $html .= '<table>';
    $html .= '<thead>';
    $html .= '<tr valign="bottom">';
    $html .= '<th width="50px" valign="bottom">Position</th>';
    $html .= '<th width="450px" valign="bottom" style="text-align: left;">Bezeichnung</th>';
    $html .= '<th width="100px" valign="bottom">Breite x H&ouml;he (mm)</th>';
    $html .= '<th width="50px" valign="bottom">Anzahl</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td style="text-align: center;" valign="top">1</td>';
    $html .= '<td style="text-align: left;">';
    $html .= '<span class="position">Acrylglas XT 5mm</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x facettierte & polierte Kante:</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">je 2mm 45&deg;</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x Rundecke</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x Wandabstandshalter:</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">Messing, poliert</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">Art. GL.000.000.001</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">2 x Bohrung</span>';
    $html .= '</td>';
    $html .= '<td style="text-align: center;">1000x1000</td>';
    $html .= '<td style="text-align: center;">2</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="last" style="text-align: center;" valign="top">2</td>';
    $html .= '<td class="last" style="text-align: left;">';
    $html .= '<span class="position">Klemmschildhalter ohne Platenbohrung</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">Messing, poliert, verchormt</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">Art. GL.3213.5454.3215</span>';
    $html .= '</td>';
    $html .= '<td class="last" style="text-align: center;"></td>';
    $html .= '<td class="last" style="text-align: center;">20</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '<tfoot>';
    $html .= '<tr>';
    $html .= '<td colspan="2" style="text-align: right;">Gesamt Platten:</td>';
    $html .= '<td>LmxBmxHmmx1.2 kg</td>';
    $html .= '<td>22 Stk.</td>';
    $html .= '</tr>';
    $html .= '</tfoot>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '<div class="footerDaten">';
    $html .= '<table border="1" style="border-collapse: collapse;margin-left: -1px;">';
    $html .= '<thead>';
    $html .= '<tr>';
    $html .= '<th>Gewicht</th>';
    $html .= '<th>Paketdienst</th>';
    $html .= '<th>Spedition</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td style="font-size: 1.3em;">&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '<table border="1" style="border-collapse: collapse;margin-left: -1px;">';
    $html .= '<thead>';
    $html .= '<tr>';
    $html .= '<th>Karton(Anzahl)</th>';
    $html .= '<th>Einwegpalette(Anzahl)</th>';
    $html .= '<th>Europalette(Anzahl)</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td style="font-size: 1em;">&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '<table border="1" style="border-collapse: collapse;margin-left: -1px;">';
    $html .= '<thead>';
    $html .= '<tr>';
    $html .= '<th>Länge(mm)</th>';
    $html .= '<th>Breite(mm)</th>';
    $html .= '<th>Höhe(mm)</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td style="font-size: 1.3em;">&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</body>';
    $html .= '</html>';
    return $html;
}

?>
