<?php

function getLs() {
    $html = '<!DOCTYPE html>';
    $html .= '<html>';
    $html .= '<head>';
    $html .= '<title></title>';
    $html .= '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
    $html .= '<link rel="stylesheet" type="text/css" href="style.css" media="all">';
    $html .= '</head>';
    $html .= '<body>';

    $html .= '<!--mpdf';
    $html .= '<htmlpageheader name="myheader">';
    $html .= '<div class="topContainer"></div>';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="header">';
    $html .= '<div class="adresse">';
    $html .= '<p>Herrn</p>';
    $html .= '<p>Max Mustermann</p>';
    $html .= '<p>Muster Str. 5</p>';
    $html .= '<p></p>';
    $html .= '<p>91522 Ansbach</p>';
    $html .= '</div>';
    $html .= '<div class="infoDaten">';
    $html .= '<p>Lieferschein-Nr. 2</p>';
    $html .= '<table>';
    $html .= '<tr>';
    $html .= '<td>zu Auftrag-Nr.</td>';
    $html .= '<td>A1</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>Kunden-Nummer</td>';
    $html .= '<td>7</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td colspan="2">&nbsp;</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>Druckdatum</td>';
    $html .= '<td>21.12.2011</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td>Bearbeiter</td>';
    $html .= '<td>Herr Dikij</td>';
    $html .= '</tr>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="barcode">';
    $html .= '<span>2</span>';
    $html .= '<barcode code="P.3.1" type="C39" class="barcode" />';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</htmlpageheader> ';

    $html .= '<sethtmlpageheader name="myheader" value="on" show-this-page="1" />';
    $html .= '<sethtmlpagefooter name="myfooter" value="on" />';
    $html .= 'mpdf-->';
    $html .= '<div class="clearer"></div>';
    $html .= '<div class="content">';
    $html .= '<div>';
    $html .= '<p style="font-weight: bold; margin-bottom: 10px;">Sehr geehrte Damen und Herren,</p>';
    $html .= '<p>Bitte überprüfen Sie die gelieferten Positionen bei Erhalt.</p>';
    $html .= '</div>';
    $html .= '<div class="positionenTabelle">';
    $html .= '<table>';
    $html .= '<thead>';
    $html .= '<tr valign="bottom">';
    $html .= '<th width="50px" valign="bottom">Position</th>';
    $html .= '<th width="280px" valign="bottom" style="text-align: left;">Bezeichnung</th>';
    $html .= '<th width="100px" valign="bottom">Breite x H&ouml;he (mm)</th>';
    $html .= '<th width="50px" valign="bottom">Anzahl</th>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td style="text-align: center;" valign="top">1</td>';
    $html .= '<td style="text-align: left;">';
    $html .= '<span class="position">Acrylglas XT 5mm</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x facettierte & polierte Kante:</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">je 2mm 45&deg;</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x Rundecke</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">4 x Wandabstandshalter:</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">Messing, poliert</span><br />';
    $html .= '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="deatail2">Art. GL.000.000.001</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">2 x Bohrung</span>';
    $html .= '</td>';
    $html .= '<td style="text-align: center;">1000x1000</td>';
    $html .= '<td style="text-align: center;">2</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="last" style="text-align: center;" valign="top">2</td>';
    $html .= '<td class="last" style="text-align: left;">';
    $html .= '<span class="position">Klemmschildhalter ohne Platenbohrung</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">Messing, poliert, verchormt</span><br />';
    $html .= '&nbsp;&nbsp;<span class="deatail1">Art. GL.3213.5454.3215</span>';
    $html .= '</td>';
    $html .= '<td class="last" style="text-align: center;"></td>';
    $html .= '<td class="last" style="text-align: center;">20</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '<tfoot>';
    $html .= '<tr>';
    $html .= '<td>Lieferbedingung:</td>';
    $html .= '<td>Selbstabholer o. Versand</td>';
    $html .= '<td style="text-align: right; padding:3px;">Gesamt</td>';
    $html .= '<td style="text-align: center; padding:3px;">22</td>';
    $html .= '</tr>';
    $html .= '<tr>';
    $html .= '<td class="last">Lieferadresse:</td>';
    $html .= '<td colspan="3" class="last">wie oben bzw. abweichende Lieferanschrift o. Leer</td>';
    $html .= '</tr>';
    $html .= '</tfoot>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '<div>';
    $html .= '<table border="0" style="border-collapse: collapse;margin-left: -1px;">';

    $html .= '</table>';
    $html .= '</div>';
    $html .= '<div style="margin-top: 10px;">';
    $html .= '<p>Bei Nachfragen bitten wir um die Angabe der zugeordneten Auftragsnummer.</p>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '</body>';
    $html .= '</html>';

    return $html;
}

?>
